spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://95.169.23.128:3306/sleep?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    properties:
      enable_lazy_load_no_trans: true
      hibernate:
        hbm2ddl:
         auto=update
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path:  /sleep

projectUrl:
  expire_time: http://sell.natapp4.cc
  wechatOpenAuthorize: http://sell.natapp4.cc
  sell: http://sell.natapp4.cc